import type { Explain } from '../../guide/guide'

type E = Explain
type Kind = 'auth' | 'rate_limit' | 'not_found' | 'network' | 'server' | 'internal'
type Item = { kind: Kind; see: string; why: string; retry: string; sample: string; explain: E }

export const errorsDict = {
  hi: {
    title: 'Errors samjho',
    sub: 'LLM connect ya run fail hone pe app yahi error types dikhata hai. Har ek ka matlab, wajah aur fix.',
    see: 'Tumhe kya dikhega', why: 'Kyun hua', retryLabel: 'Retry?', fixes: 'Fix',
    simulate: 'Simulate karo', hideSim: 'Chhupao', settings: 'Settings', offline: 'Offline demo', addFallback: 'Fallback jodo',
    offlineDone: 'Offline demo chalu',
    retryYes: 'Haan, RetryingLLM backoff ke saath retry karta hai', retryNo: 'Nahi, seedha fail ya fallback',
    tipSim: 'Kisi bhi error pe "Simulate karo" dabao: dekho woh card kaisa dikhta hai.',
    flowTitle: 'Error ka safar',
    flow: ['Provider HTTP error', 'LLMError(status, retryable)', 'RetryingLLM / FallbackLLM', 'labapi classify_error', 'UI LabError card'],
    items: [
      { kind: 'auth', see: '401 / 403 "Invalid API key". Missing key pe bhi yahi (ValueError: needs GROQ_API_KEY).', why: 'Key galat, expire ya galat provider ki hai. retryable=False, isliye retry nahi hota: dobara bhejne se key sahi nahi hogi.', retry: 'no', sample: 'groq HTTP 401: {"error":{"message":"Invalid API Key","type":"invalid_request_error"}}', explain: { title: '401: key galat hai', flow: ['HTTP 401', 'LLMError(retryable=False)', 'classify_error -> auth'], lines: ['openai_compat.py 401 ko LLMError(status=401, retryable=False) banata hai.', 'RetryingLLM retry nahi karta; FallbackLLM ho to agla provider try hota hai.', 'labapi registry isse kind="auth" deta hai aur UI Settings ka raasta dikhata hai.'], file: 'common/agentkit/llm/openai_compat.py' } },
      { kind: 'rate_limit', see: '429 "Rate limit reached". Free tiers pe bahut aam, khaas kar jaldi-jaldi runs pe.', why: 'Provider ne per-minute limit laga di. retryable=True: RetryingLLM 1s, 2s, 4s (+jitter) ruk ke retry karta hai.', retry: 'yes', sample: 'groq HTTP 429: {"error":{"message":"Rate limit reached for model llama-3.3-70b-versatile. Please try again in 7.2s."}}', explain: { title: '429: rate limit', flow: ['HTTP 429', 'RetryingLLM backoff', 'FallbackLLM', 'classify_error -> rate_limit'], lines: ['RetryingLLM exponential backoff + jitter ke saath retry karta hai (resilient.py).', 'Retries khatam ho gaye to FallbackLLM agla provider try karta hai; chain nahi hai to error UI tak aata hai.', 'Fix: thoda ruko, ya Settings mein fallback provider jodo.'], file: 'common/agentkit/llm/resilient.py' } },
      { kind: 'not_found', see: '404 "model not found". Model ka naam galat ya tumhare account pe available nahi.', why: 'Spec mein model id provider ke paas nahi hai. 4xx hai, retry bekaar.', retry: 'no', sample: 'gemini HTTP 404: {"error":{"code":404,"message":"models/gemini-9 is not found"}}', explain: { title: '404: model nahi mila', flow: ['spec provider:model', 'HTTP 404', 'classify_error -> not_found'], lines: ['get_llm("provider:model") model id seedha provider ko bhejta hai (factory.py).', 'Galat id pe provider 404 deta hai; retry se kuch nahi badlega.', 'Fix: Settings mein dusra provider/model chuno.'], file: 'common/agentkit/llm/factory.py' } },
      { kind: 'network', see: '"network error or CORS blocked". Internet band, provider unreachable, ya site browser calls allow nahi karti.', why: 'Browser mein request fail hone pe http.py TransportError uthata hai; adapter isse LLMError(status=None, retryable=True) banata hai.', retry: 'yes', sample: 'groq network error: browser request failed (network error or CORS blocked)', explain: { title: 'Network / CORS error', flow: ['sync XHR', 'status 0', 'TransportError', 'classify_error -> network'], lines: ['Browser worker sync XMLHttpRequest use karta hai (common/agentkit/llm/http.py).', 'Internet gaya ya CORS block hua to status 0 aata hai: TransportError, phir retry.', 'Fix: connection check karo, ya Offline demo pe switch karo.'], file: 'common/agentkit/llm/http.py' } },
      { kind: 'server', see: '500 / 502 / 503 / 529 "overloaded". Provider ki taraf dikkat.', why: '5xx retryable=True hai (Anthropic ka 529 bhi). Thodi der mein aksar theek ho jaata hai.', retry: 'yes', sample: 'anthropic HTTP 529: {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}', explain: { title: '5xx: provider down', flow: ['HTTP 5xx', 'RetryingLLM', 'FallbackLLM', 'classify_error -> server'], lines: ['5xx aur 529 retryable hain, isliye RetryingLLM backoff ke saath dobara try karta hai.', 'Production mein isi liye fallback chain rakhte hain: ek provider down, dusra chalu.'], file: 'common/agentkit/llm/resilient.py' } },
      { kind: 'internal', see: 'Python exception, jaise ValueError ya KeyError. Card mein trace ka hissa bhi aata hai.', why: 'LLM se nahi, lab ya project code se aaya. labapi.run() isse pakad ke kind="internal" deta hai taaki UI crash na ho.', retry: 'no', sample: 'KeyError: \'choices\'', explain: { title: 'Internal error', flow: ['Python exception', 'labapi.run try/except', 'classify_error -> internal'], lines: ['labapi.run() kabhi exception bahar nahi phenkta; hamesha {ok: false, error} lautaata hai.', 'Aisa error bug ho sakta hai: Offline demo try karo, aur issue GitHub pe daalo.'], file: 'lab-api/labapi/registry.py' } },
    ] as Item[],
  },
  en: {
    title: 'Understand errors',
    sub: 'These are the error types the app shows when connecting to an LLM or running a lab fails. What each one means, why it happens, and how to fix it.',
    see: 'What you see', why: 'Why it happens', retryLabel: 'Retry?', fixes: 'Fix',
    simulate: 'Simulate', hideSim: 'Hide', settings: 'Settings', offline: 'Offline demo', addFallback: 'Add a fallback',
    offlineDone: 'Offline demo on',
    retryYes: 'Yes, RetryingLLM retries with backoff', retryNo: 'No, fails fast or falls back',
    tipSim: 'Click "Simulate" on any error to see what that card looks like.',
    flowTitle: 'How an error travels',
    flow: ['Provider HTTP error', 'LLMError(status, retryable)', 'RetryingLLM / FallbackLLM', 'labapi classify_error', 'UI LabError card'],
    items: [
      { kind: 'auth', see: '401 / 403 "Invalid API key". A missing key gives the same (ValueError: needs GROQ_API_KEY).', why: 'The key is wrong, expired or for another provider. retryable=False, so there is no retry: resending will not fix the key.', retry: 'no', sample: 'groq HTTP 401: {"error":{"message":"Invalid API Key","type":"invalid_request_error"}}', explain: { title: '401: invalid key', flow: ['HTTP 401', 'LLMError(retryable=False)', 'classify_error -> auth'], lines: ['openai_compat.py turns a 401 into LLMError(status=401, retryable=False).', 'RetryingLLM does not retry; with a FallbackLLM the next provider is tried.', 'The labapi registry maps it to kind="auth" and the UI points you to Settings.'], file: 'common/agentkit/llm/openai_compat.py' } },
      { kind: 'rate_limit', see: '429 "Rate limit reached". Very common on free tiers, especially with rapid runs.', why: 'The provider hit a per-minute limit. retryable=True: RetryingLLM waits 1s, 2s, 4s (+jitter) and retries.', retry: 'yes', sample: 'groq HTTP 429: {"error":{"message":"Rate limit reached for model llama-3.3-70b-versatile. Please try again in 7.2s."}}', explain: { title: '429: rate limited', flow: ['HTTP 429', 'RetryingLLM backoff', 'FallbackLLM', 'classify_error -> rate_limit'], lines: ['RetryingLLM retries with exponential backoff plus jitter (resilient.py).', 'When retries run out, FallbackLLM tries the next provider; with no chain the error reaches the UI.', 'Fix: wait a bit, or add a fallback provider in Settings.'], file: 'common/agentkit/llm/resilient.py' } },
      { kind: 'not_found', see: '404 "model not found". The model name is wrong or not available on your account.', why: 'The model id in the spec does not exist at the provider. It is a 4xx, so retrying is useless.', retry: 'no', sample: 'gemini HTTP 404: {"error":{"code":404,"message":"models/gemini-9 is not found"}}', explain: { title: '404: model not found', flow: ['spec provider:model', 'HTTP 404', 'classify_error -> not_found'], lines: ['get_llm("provider:model") sends the model id straight to the provider (factory.py).', 'A wrong id gets a 404; retrying changes nothing.', 'Fix: pick another provider or model in Settings.'], file: 'common/agentkit/llm/factory.py' } },
      { kind: 'network', see: '"network error or CORS blocked". No internet, provider unreachable, or the site does not allow browser calls.', why: 'When a browser request fails, http.py raises TransportError; the adapter turns it into LLMError(status=None, retryable=True).', retry: 'yes', sample: 'groq network error: browser request failed (network error or CORS blocked)', explain: { title: 'Network / CORS error', flow: ['sync XHR', 'status 0', 'TransportError', 'classify_error -> network'], lines: ['The browser worker uses a synchronous XMLHttpRequest (common/agentkit/llm/http.py).', 'If the internet drops or CORS blocks the call, the status is 0: TransportError, then retry.', 'Fix: check your connection, or switch to the Offline demo.'], file: 'common/agentkit/llm/http.py' } },
      { kind: 'server', see: '500 / 502 / 503 / 529 "overloaded". A problem on the provider’s side.', why: '5xx are retryable=True (so is Anthropic’s 529). It usually recovers in a bit.', retry: 'yes', sample: 'anthropic HTTP 529: {"type":"error","error":{"type":"overloaded_error","message":"Overloaded"}}', explain: { title: '5xx: provider down', flow: ['HTTP 5xx', 'RetryingLLM', 'FallbackLLM', 'classify_error -> server'], lines: ['5xx and 529 are retryable, so RetryingLLM tries again with backoff.', 'This is why production agents keep a fallback chain: one provider down, another up.'], file: 'common/agentkit/llm/resilient.py' } },
      { kind: 'internal', see: 'A Python exception such as ValueError or KeyError. The card also shows part of the trace.', why: 'It came from the lab or project code, not the LLM. labapi.run() catches it and returns kind="internal" so the UI does not crash.', retry: 'no', sample: 'KeyError: \'choices\'', explain: { title: 'Internal error', flow: ['Python exception', 'labapi.run try/except', 'classify_error -> internal'], lines: ['labapi.run() never lets an exception escape; it always returns {ok: false, error}.', 'An error like this may be a bug: try the Offline demo, and open an issue on GitHub.'], file: 'lab-api/labapi/registry.py' } },
    ] as Item[],
  },
}
